$wallpaper = /home/conspiration3001/.config/wallpapers/fingers.jpg

$background = rgb(11131a)
$foreground = rgb(e1e2eb)

$color0 = rgb(0b0e15)
$color1 = rgb(adc6ff)
$color2 = rgb(b1c6f7)
$color3 = rgb(f4aeff)
$color4 = rgb(4d8efe)
$color5 = rgb(344972)
$color6 = rgb(c66dda)
$color7 = rgb(c2c6d5)
$color8 = rgb(8c909f)
$color9 = rgb(adc6ff)
$color10 = rgb(b1c6f7)
$color11 = rgb(f4aeff)
$color12 = rgb(4d8efe)
$color13 = rgb(344972)
$color14 = rgb(c66dda)
$color15 = rgb(e1e2eb)
